### ISSUE TITLE
Error message when starting GIMP in bash mode

### ISSUE THREAD

**Issue by barrynerd** [khalim19/gimp-plugin-export-layers#12]
Hi Khalim - Since my earlier post I have been working with your plugin and adjustng my workflow accordingly. So far, so good!

I have been working to create python-fu scripts that will manage my workflow, while using your plugin to handle the output.

This requires starting gimp from the command line, and when I do so I get an error:

-----------------------_
$ gimp -id 
GIMP-Error: Unable to run plug-in "export_layers"
(/home/barry/.gimp-2.8/plug-ins/export_layers)
## Failed to execute child process "/home/barry/.gimp-2.8/plug-ins/export_layers" (Permission denied)

Still, it seems to be available to my script and it works. And interactive mode works fine, as you already know.

Since I am new to to gimp python-fu, I am not exactly sure why this is. My guess is that it is related to a folder that exists in my plugins folder called export export_layers that holds a lot of your code. Seems the right way to factor code to me, but maybe because not all of the files in the folder are executable, or maybe because some of them all, the message is displayed?

In any case, this won't hold me up, I can live with it and once my code is stable, I can redirect stderr to /dev/null if need be.

But I thought you might have some ideas, or at least should know about it, because I think this is a very useful plugin and concept that could see wide use once it is known. At that point, the error might become a sticking point to some.

Cheers!

**Comment by nouyang** [comment]
@notwendig , how did you patch it? I have the same issue.

    GIMP-Error: Unable to run plug-in "export_layers"
    (/home/nrw/.gimp-2.8/plug-ins/export_layers)
    Failed to execute child process "/home/nrw/.gimp-2.8/plug-ins/export_layers" (Permission denied)

ls -la 

    drwxrwxrwx  4 nrw nrw  4096 Feb  6 16:32 export_layers
    -rwxr-xr-x  1 nrw nrw 23826 Dec 19 20:47 export_layers.py

python version 2.7.6
gimp 2.8

I changed DEBUG to true in export_layers/constants.py but do not see any log files in pygimplib.

    $ sudo gimp

does not work either ^^;

**Comment by nouyang** [comment]
Update: `$ gimp` still spits the error message out, but the plugin now appears in `File > Export Layers` and works. I dunno, maybe I just had to restart GIMP a few more times (I am 100% certain that previously, it would spit the error message out and would NOT appear in the File menu). 

_shrug_ computers...

**Comment by jmunsch** [comment]
+1

**Comment by khalim19** [comment]
@jmunsch Yeah, those warnings now pop up since 2.4. I could not get rid of them, but as far as I can tell, they are harmless.

**Comment by khalim19** [comment]
Closing this issue since GIMP 2.10 now supports having directories with the same name as the plug-in file in the `plug-ins` folder (in this case, `export_layers`). As a result, this plug-in no longer throws error messages while GIMP is being initialized.
