### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by stigzler** [khalim19/gimp-plugin-export-layers#19]
HI,
This plugin looks great, but can't get it working. 
Using Gimp 2.8.14 64 bit. Windows

Have installed
export_layers.py 
export_layers (folder)
to:
C:\Program Files\Gimp-2.8\lib\gimp\2.0\plug-ins
(the directory "`[home directory]/.gimp-2.8/plug-ins`" (from readme) doesn't exist on my machine)

When I start Gimp - there is no "Export Layers" option under File. Essentially can't run this script. Could you please advise?

**Comment by Horemheb** [comment]
Not working. Neither with the official new release of gimp nor with the new release of your plugin. copyed the plugin only in the user folder. Not working. :( I can't see Export Layers chooseable. :( This plugin seems to be everything but easy to get to work. :( Pity :(

**Comment by Horemheb** [comment]
Eating my typed intervention back Khalim19! LOL
It started to work by itself now..
:)
So.. sorry for bothering you. This morning it really didn't seem to want to work at all
Thanks for everything!
Yours Horemheb...

**Comment by khalim19** [comment]
No problem, I'm glad you got it working. :)

**Comment by khalim19** [comment]
Closing this as no further information was provided to the original issue.
