### ISSUE TITLE
"Type a file name" button

### ISSUE THREAD

**Issue by Nomadjackalope** [khalim19/gimp-plugin-export-layers#20]
When I use the button that allows the user to type in a location and press the Enter key the plugin will use the current location and will not change to the new one. It would not be a problem except that I am trying to use AutoIt to automate some repetitive tasks and want to type in this location.

![export_tool_help](https://cloud.githubusercontent.com/assets/10321632/5560788/f9e86434-8d5c-11e4-861e-6fd91a3d3e04.PNG)

Using Windows 7
Gimp 2.8.14

**Comment by khalim19** [comment]
Incorporated in version 2.3.
