### ISSUE TITLE
Error while saving < filename > . Could not save Image.

### ISSUE THREAD

**Issue by mravikiran** [khalim19/gimp-plugin-export-layers#22]
Hi Khalim, 
I am fairly new to GIMP. However I found your plugin very useful for the side project i am doing. I tried to use your plugin through gimp. I imported a PSD file and was trying to export the layers as png's. I am getting this error message
![gimp_save_error](https://cloud.githubusercontent.com/assets/5799359/6888392/644dff46-d641-11e4-8aec-0f17559f07a6.png)
Basically for some reason the file is not getting saved. I have checked the permissions of the folders that does not seem to be a problem.
I am on GIMP version 2.8.10 and python 2.7.6. 

Thanks,
Ravi

**Comment by khalim19** [comment]
Hello Ravi,
first of all I apologize for the late reply, I was busy working on other projects (which took priority).

Have you tried exporting in a different file format?
Do you still get the error message when you export a layer or an image in PNG using the GIMP's export menu?

**Comment by khalim19** [comment]
Closing this as no further information was provided to the original issue.
