### ISSUE TITLE
Plug-in crashed: "export_layers.py"

### ISSUE THREAD

**Issue by louisgv** [khalim19/gimp-plugin-export-layers#23]
OS: Windows 8.1
Gimp version: 2.8.14

Description: 
Upon clicking either options (export layer to or export layer), pythonw.exe crashed.

Message:
Plug-in crashed: "export_layers.py"
(C:\Users\Louis\.gimp-2.8\plug-ins\export_layers.py)

The dying plug-in may have messed up GIMP's internal state. You may want to save your images and restart GIMP to be on the safe side.

**Comment by khalim19** [comment]
Try reinstalling GIMP.

There have been [a few](https://github.com/khalim19/gimp-plugin-export-layers/issues/14) [reports](https://github.com/khalim19/gimp-plugin-export-layers/issues/21) like this. If reinstalling GIMP doesn't resolve the crash, I'd be grateful if you followed instructions in [this post](https://github.com/khalim19/gimp-plugin-export-layers/issues/14#issuecomment-102420948) and reported to me with results, as it could help me track down the issue.

**Comment by khalim19** [comment]
Closing this as no further information was provided to the original issue.
