### ISSUE TITLE
Export layers choice keeps being unavailable

### ISSUE THREAD

**Issue by Horemheb** [khalim19/gimp-plugin-export-layers#24]
Hello
I did as indicated in the download webpage.
I overwrote the files in the plugin folder.
Nothing changes.
Export Layers is not available. Keeps being transparent. 
How come?
Thanks in advance
:)

**Comment by khalim19** [comment]
Hello,

what directory did you install the plug-in into?

By being transparent, do you mean that the "Export Layers" menu is greyed out or not displayed at all? You should find it under the "File" menu.

If you're running the plug-in on Linux or OS X, make sure the `export_layers.py` file is executable. Also make sure that you copy the `export_layers` directory as well, not just the `export_layers.py` file.

**Comment by khalim19** [comment]
[Resolved](https://github.com/khalim19/gimp-plugin-export-layers/issues/19#issuecomment-122667684).
