### ISSUE TITLE
Invalid caracters? Seriously?

### ISSUE THREAD

**Issue by kogolbok** [khalim19/gimp-plugin-export-layers#27]
Hello.
plugin does not starting. In export_layers_error.log I found this:
>Export Layers
>2015-10-18 10:12:31.900320
>
>Traceback (most recent call last):
>  File "/home/kostia/.config/GIMP/2.9/plug-ins/export_layers.py", line 176, in <module>
>    ExportLayersPlugin().start()
>  File "/home/kostia/.config/GIMP/2.9/plug-ins/export_layers.py", line 63, in __init__
    self.settings = settings_plugin.create_settings()
>  File "/home/kostia/.config/GIMP/2.9/plug-ins/export_layers/settings_plugin.py", line 183, in >create_settings
>    'display_name': _("Overwrite mode (non-interactive run mode only)")
>  File "/home/kostia/.config/GIMP/2.9/plug-ins/export_layers/pygimplib/pgsettinggroup.py", line 99, in __init__
>    self.add(setting_list)
>  File "/home/kostia/.config/GIMP/2.9/plug-ins/export_layers/pygimplib/pgsettinggroup.py", line 189, in add
>    self._create_setting(setting_or_group)
>  File "/home/kostia/.config/GIMP/2.9/plug-ins/export_layers/pygimplib/pgsettinggroup.py", line 329, in _create_setting
>    self._settings[setting_data['name']] = setting_type(**setting_data)
>  File "/home/kostia/.config/GIMP/2.9/plug-ins/export_layers/pygimplib/pgsetting.py", line 1046, in __init__
>    super(DirectorySetting, self).__init__(name, default_value, pgpath.FilePathValidator, **kwargs)
>  File "/home/kostia/.config/GIMP/2.9/plug-ins/export_layers/pygimplib/pgsetting.py", line 979, in __init__
>    super(ValidatableStringSetting, self).__init__(name, default_value, **kwargs)
>  File "/home/kostia/.config/GIMP/2.9/plug-ins/export_layers/pygimplib/pgsetting.py", line 248, in __init__
>    self._validate_default_value()
>  File "/home/kostia/.config/GIMP/2.9/plug-ins/export_layers/pygimplib/pgsetting.py", line 474, in _validate_default_value
>    raise SettingDefaultValueError(e.message)
>SettingDefaultValueError: "/home/kostia/Документы": File path contains invalid characters.
(Tried it first in GIMP 2.8, now updated to 2.9 daily builds, but I think it doesn't matter in this case)

The problem is that it doesn't understand non ASCII characters? Don't you think that these characters are not invalid, they are non latinic? :) And python easily operates with this kind of simbols, as far as I know.
And in any way, why is it checking my default path during plugin initialisation and stopping it from being loaded? If it can't be fixed to understand UTF-8 characters, then, please, let me choose the right folder during file export, not stopping plugin from being loaded.

(Sory for my English)

**Comment by khalim19** [comment]
Are you using the latest version of the plug-in (2.4)? It should already be fixed.

**Comment by kogolbok** [comment]
Oh, thank you. Yes, it is fixed now.
Many thanks for the plugin!

**Comment by khalim19** [comment]
Great to hear that. :)
