### ISSUE TITLE
Feature: Foreground layers

### ISSUE THREAD

**Issue by Gfurst** [khalim19/gimp-plugin-export-layers#29]
There is the background layer feature to set same background, but why not have a foreground equivalent as option for bracket layers. 
Such feature would be useful for example to apply a same color effect to several images or something similar.

**Comment by khalim19** [comment]
Sounds good to me.

In case a user wants both background and foreground layers, we can't use the square brackets as we wouldn't be able to distinguish them. This will require some other way to tag layers as foreground layers, perhaps double square brackets.

**Comment by Gfurst** [comment]
nice @khalim19, 
maybe match strings 'background' and 'foreground' if user wants to use both.

**Comment by khalim19** [comment]
Implemented in 2.5.
