### ISSUE TITLE
Feature: add option "export per layer" to layer tab

### ISSUE THREAD

**Issue by mroeling** [khalim19/gimp-plugin-export-layers#32]
Working great! 
I have a feature request: add an option to the layer tab context menu, to be able to export a single layer. That way it is also possible to use per layer export settings, as mentioned [here](https://github.com/khalim19/gimp-plugin-export-layers/issues/13).

**Comment by khalim19** [comment]
I imagine you could first set up settings in the Export Layers dialog, save the settings and then use the new menu to export the one layer.

The question is, should we display the file format dialog at each export? Or have two separate menu options again, one for explicitly defining the file format settings and another one for repeating the export?

It's going to take quite a long time before I can implement this, though. I am really busy these days (or, rather, months)...

**Comment by khalim19** [comment]
Given the [layer name preview I recently added in the plug-in](https://github.com/khalim19/gimp-plugin-export-layers/issues/35), I'm now leaning toward a different solution: select the desired layer directly in the preview. That way, you only work with a single window/menu and you can also select multiple layers to export.

**Comment by khalim19** [comment]
Done (sort of). To export selected layers, simply check "Export only selected layers" and select the desired layers in the preview.

What's left to do is to enable exporting individual non-top-level layer groups as images. The "Merge layer groups" setting only accounts for the top-level groups.

**Comment by khalim19** [comment]
Done. The individual layer settings are going to be dealt with in a later version.
