### ISSUE TITLE
Can't export when first layer's name end with .png

### ISSUE THREAD

**Issue by Ravaelles** [khalim19/gimp-plugin-export-layers#40]
I'm using option `Open files as layers` and it creates layers with names of the files. Every layer name ends with .png and it causes infinite waiting for the quality dialog box input. When you change name of the first layer so it doesn't contain ".png" part, it works (all layers can have .png in it.

**Comment by khalim19** [comment]
I assume you mean the PNG file format dialog - in that case, check if the dialog isn't displayed behind GIMP. This unfortunately happens sometimes and I haven't found a way to fix it for good.
