### ISSUE TITLE
New layers on repeated exports aren't added if "skip" is chosen for the last repeat layer.

### ISSUE THREAD

**Issue by bfedie518** [khalim19/gimp-plugin-export-layers#46]
When you export the layers of a picture more than once, if there are new layers, they aren't always exported. 
When the plug-in asks what you would like to do with the layer files that already exist, if you click "skip" on the last already existing file (what you pick on the others doesn't matter) it will not export any more layers.
If you click "replace" or any of the other options, all layers are exported normally.
This happens consistently, and also affects any new groups if you have "treat layer groups as folders" selected.

**Comment by khalim19** [comment]
Thanks for the report. This also happens if the new layers are not the last in the layer tree.
