### ISSUE TITLE
Name field doesn't appear on MacOS

### ISSUE THREAD

**Issue by Medtrack** [khalim19/gimp-plugin-export-layers#53]
#### What went wrong?

Export dialog doesn't allow to change name on MacOS. It is different from the one here:
https://khalim19.github.io/gimp-plugin-export-layers/sections/Advanced-Usage#dialog

#### If you can, tell us the steps to reproduce the problem.
- Install the plugin as is mentioned in the Readme.txt. The way in the  [docs](https://khalim19.github.io/gimp-plugin-export-layers/sections/Installation.html#os-x)
is for a different version, I guess.
- Create an image with several layers.
- Run file/export layers

Export layers dialog is different to the one in the docs:
<img width="856" alt="export-layers-screenshot" src="https://user-images.githubusercontent.com/17614549/37459642-09b091e0-2849-11e8-9152-862ea38ace33.png">

#### Configuration

Version of Export Layers: 
2.5
Version of GIMP: 
2.8
Operating system: 
MacOS High Sierra

**Comment by khalim19** [comment]
The documentation is for 3.0-RC2  (not 2.5 or lower), which contains the name field (among other new features).

Sorry about the confusion. You can already use 3.0-RC2, it's pretty stable and usable as-is, I just need to fix one elusive bug and make a few adjustments before 3.0 is released.

**Comment by Medtrack** [comment]
Ok. Thanks for your reply. I will try next version. It was not a problem, I just opened the issue in case it was a bug. 
Sorry for the inconvenience :-)
