### ISSUE TITLE
(Solved) This plug in not working with 2.10

### ISSUE THREAD

**Issue by GitMepc7r** [khalim19/gimp-plugin-export-layers#55]
The menu File - does not show Export Layers To/ Export Layers after pasting the py file and the folder in the GIMP 2\lib\gimp\2.0\plug-ins as instructed in the readme, so it is not recognized or installed in GIMP.

#### Configuration

Version of Export Layers: Latest download

Version of GIMP: 2.10

Operating system: Windows 10 x64, (latest) update

**Comment by khalim19** [comment]
By latest download, do you mean version 3.1?

**Comment by jugdemon** [comment]
I think the issue is with the plugin registry: http://registry.gimp.org/node/28268

It links anyone to the download of the 2.4 file. Updating the registry would help users getting the right version.

**Comment by khalim19** [comment]
Unfortunately, I cannot remove or update the page in the GIMP Plugin Registry anymore as the site went static.

What I can do for now is to update the template for issues to make sure users download the plug-in from GitHub rather than the plugin registry.

**Comment by GitMepc7r** [comment]
Ok the issue was indeed using older version. Let's link the one that works with 2.10 and that is the plugin 3.1 (and onward)
https://github.com/khalim19/gimp-plugin-export-layers/releases
