### ISSUE TITLE
Version 3.1 does not work with GIMP 2.10.0

### ISSUE THREAD

**Issue by ryankane** [khalim19/gimp-plugin-export-layers#57]
This is a critical plugin and I am surprised that it has not been adopted by the official GIMP team.

### Actions taken

I performed a clean install of GIMP. I upgraded from 2.8 and removed all old settings and configurations.

I even removed my `pluginrc` file and restarted GIMP and it still did not pick up the plugin. I did not see it listed in that file.

I installed the plugin files: `export_layers/` and `export_layers.py` to `%AppData%\GIMP\2.10\plug-ins`.

### Stacktrace

I ran GIMP in verbose mode. It looks like the `gimp_wire_read` error caused the plugin to not even load.

```
C:\Program Files\GIMP 2\bin\gimp-2.10.exe" --verbose
...
Querying plug-in: 'C:\Users\ryan\AppData\Roaming\GIMP\2.10\plug-ins\export_layers.py'
C:\Program Files\GIMP 2\bin\gimp-2.10.exe: LibGimpBase-WARNING: gimp-2.10.exe: gimp_wire_read(): error
```

I found a post about this error through a quick Google search. I believe that the strings references in the script may not be escaped properly.

> [GIMP - “windows 10” - “command line” - error][1]

### See also

There is an open discussion of this issue on the GIMP forums.

> [Export-Layers Plugin not working with 2.10?][2]

  [1]: http://gimpforums.com/thread-gimp-%E2%80%9Cwindows-10%E2%80%9D-%E2%80%9Ccommand-line%E2%80%9D-error
  [2]: https://www.gimp-forum.net/Thread-Export-Layers-Plugin-not-working-with-2-10

**Comment by khalim19** [comment]
Try the workaround discussed [here](https://github.com/khalim19/gimp-plugin-export-layers/issues/56).

**Comment by khalim19** [comment]
No problem. :) I should have left the issue open until the release.
