### ISSUE TITLE
New constraint: Only projections of layer groups

### ISSUE THREAD

**Issue by prokoudine** [khalim19/gimp-plugin-export-layers#58]
Unless I'm missing something, it isn't possible to export just the layer groups, with all its contents flattened in the output.

E.e. I have layer group '1' with '1.1' and '1.2' child layers, then layer group '2' with '2.1' and '2.2' child layers etc. And I want just PNGs for '1', '2' etc.

**Comment by khalim19** [comment]
Exporting just the layer groups should be already possible:
1. Add "Include -> Include layers" and uncheck (it's checked by default)
2. Add "Include -> Include layer groups" and check
3. Add "Only top-level layers"

This exports merged layer groups. It does not perform flattening, though.

**Comment by strixaluco** [comment]
@khalim19, thank you for such a great plugin. I'm wondering if it's possible to achieve same goal, as @prokoudine described, but including foreground and background layers as well, given following layers structure:
```
1
-1.1
-1.2
2
-2.1
-2.2
F
B
```

The end results should be F1B.png, F2B.png

Thank you

**Comment by strixaluco** [comment]
It seems that `Only top-level layers` constraint should help to achieve this, but in my case neither enabling nor disabling has any effect.

**Comment by khalim19** [comment]
You should be able to achieve this as follows:
1. Add `Insert foreground layers` procedure.
2. Add `Insert background layers` procedure.
3. In the preview to the right, select your foreground layers and tag them with the `Foreground` tag.
4. Perform step 3 for background layers, using the `Background` tag.
5. Add `Only top-level layers`.
6. Add `Include layer groups` so that the layer groups get exported. This may be why enabling `Only top-level layers` did not have any effect.
7. Optionally disable `Include layers` to avoid exporting the background and foreground as images.

**Comment by strixaluco** [comment]
Thank you for help, @khalim19. After updating to 3.3.1 I'm able to achieve this target. 
The only difference is that neither `Insert foreground layers` nor `Insert background layers` procedure overrides disabled `Include layers` constraint, so I had to leave layers included and remove those subsequent foregrounds and backgrounds after export.

**Comment by khalim19** [comment]
You're right, I forgot that Include layers must still be enabled. You should be able to remove fore- and background layers by adding `Only layers without tags`. If you use custom tags, edit the constraint and add "background" and "foreground" for the `Tags` parameter to ignore only background and foreground layers.

**Comment by strixaluco** [comment]
I was too excited with even half-baked solution and haven't checked all the combinations. Of course `Only layers without tags` will do the job — you are totally right. Thanks again!

**Comment by khalim19** [comment]
Closing this due to the original issue being (supposedly) resolved. I updated the original question in case flattening is desired, which is now possible given that any GIMP PDB procedure can be added.
