### ISSUE TITLE
Installer fails in non-English locales

### ISSUE THREAD

**Issue by JanisE** [khalim19/gimp-plugin-export-layers#59]
#### What went wrong?

Cannot install.

```
$ ./export_layers-3.2.1-linux.run -- --gimp-command /usr/bin/gimp --install-path /home/janis/.gimp-2.8/plug-ins/
Verifying archive integrity...  100%   All good.
Uncompressing Export Layers - GIMP plug-in  100%  
./installer.sh: 91: [: -ge: unexpected operator

Error: The specified GIMP installation ('/usr/bin/gimp') is not supported. Please install GIMP 2.8 or later or specify custom path to GIMP with the -g option and the plug-in installation path with the -i option.
[..]
```

#### If you can, tell us the steps to reproduce the problem.

I'm using a non-English locale, that does not containt word "version" in `gimp --version` output, so plug-in's installer does not recognize the GIMP version.

This will not work:
```
echo 'GNU attēlu apstrādes programma versija 2.8.14' | sed -n '/.*version [0-9][0-9]*\.[0-9][0-9]*\..*$/ { s/.*version \([0-9][0-9]*\)\.\([0-9][0-9]*\)\..*$/\1.\2/p; q; }'
```

This would work (`version` instead of `versija`):
```
echo 'GNU attēlu apstrādes programma version 2.8.14' | sed -n '/.*version [0-9][0-9]*\.[0-9][0-9]*\..*$/ { s/.*version \([0-9][0-9]*\)\.\([0-9][0-9]*\)\..*$/\1.\2/p; q; }'
```

I would propose a regexp like this instead: 
```
sed -n '/.*\b[0-9][0-9]*\.[0-9][0-9]*\..*$/ { s/.*\b\([0-9][0-9]*\)\.\([0-9][0-9]*\)\..*$/\1.\2/p; q; }'
```

#### Configuration

Version of Export Layers: 3.2.1
Version of GIMP: 2.8
Operating system: Linux Mint 17.3

**Comment by khalim19** [comment]
Thanks for the report, I had a hunch that regex would sooner or later fail for some installations. Will fix and reupload installers soon(-ish).

**Comment by khalim19** [comment]
Should be fixed now. I also modified the regex for Python version check accordingly just in case.
