### ISSUE TITLE
Merge Down Layer Folder Before Exporting

### ISSUE THREAD

**Issue by dar72** [khalim19/gimp-plugin-export-layers#66]
Is it possible to add an option to merge down all layers in each folder before exporting it as a single image?

This is for working on game graphics, say I have a folder structure like this....

```
├── Body
│   ├── Body Outline
│   ├── Body Shading
├── Left Arm
│   ├── L Outline
│   ├── L Shading
├── Right Arm
│   ├── R Outline
│   ├── R Shading
```

I'd like to export that as three images, one for each folder, often my graphics are a lot more complicated than this containing a lot more options all separated into folders so having a script to export them would save a lot of time.

**Comment by khalim19** [comment]
This should already be doable (looks like the same request as issue #58.). Try the following:

1. Add "Include -> Include layers" and uncheck (it's checked by default).
2. Add "Include -> Include layer groups" and check.
3. Add "Only top-level layers" and check.

**Comment by dar72** [comment]
Thanks, that works!
