### ISSUE TITLE
Save PNG file with position information (x, y, w, h)

### ISSUE THREAD

**Issue by friendlyranxiao** [khalim19/gimp-plugin-export-layers#68]
This plug in is marvelous, thank you so much
now I can  export each layer in .png files easily.

I was wondering if you can add a future that save the layer position information(x,y,w,h ) as file name when exported.

**Comment by khalim19** [comment]
This is should be relatively easy to do. I'll add this feature in the next release.

**Comment by slevy85** [comment]
Thank you very much, I was just going to ask for the same thing.

My need is to have position and width information so I can use it in a css file. 
It could be very interesting to have the positions and width in percentage not just in pixels.

Thank you.

**Comment by khalim19** [comment]
Version 3.3.1 now supports specifying layer attributes (using the `[attribute]` field), both as pixels and percentages relative to the image width and height.
