### ISSUE TITLE
ubuntu 18.10, gimp 2.10.6 not visible in menu

### ISSUE THREAD

**Issue by peon501** [khalim19/gimp-plugin-export-layers#73]
#### What went wrong?
I cant see export layer option on file menu

#### If you can, tell us the steps to reproduce the problem.
I just basicly downloaded this plugin and put it to
'/home/user-name/.config/GIMP/2.10/plug-ins/' dir

plug-ins folder now have 1 phython file
export_layers.py
and dir 
export_layers with a lot of py files

#### Configuration

Version of Export Layers: 
3.3.1
Version of GIMP: 
gimp 2.10.6
Operating system: 
ubuntu 18.10
Gimp installed from Ubuntu Software

**Comment by peon501** [comment]
nevermind reinstalled other program and then realized its other dir '/home/user-name/snap/gimp/130/.config/GIMP/2.10/plug-ins/'

**Comment by khalim19** [comment]
Yeah, the installation path varies across GIMP packages, it seems. I ought to update the installation instructions to always locate the `plug-ins` folder path within GIMP to avoid users installing the plug-in to the wrong folder.
