### ISSUE TITLE
Exporting Layer Groups as separate images ontop of set background

### ISSUE THREAD

**Issue by stigzler** [khalim19/gimp-plugin-export-layers#77]
Hi,

I'm wondering if this is the same plugin that I used here:
http://magoarcade.org/docs/doku.php?id=software:gameexthemeeditor:start

Pic of the 'old' settings:
http://magoarcade.org/docs/lib/exe/fetch.php?media=mediaexport.png

I'm back to this now for a new gimp project, but if it is the same plugin, the settings have changed a lot! I'm trying to achieve the same thing. Have a single Background image and then export a separate image for each Layer Group (i.e. a composite of the layer group and the background) - should be able to do in  a batch run. Here's my layout:

![exportlayers1](https://user-images.githubusercontent.com/4856029/65394637-4423d300-dd88-11e9-8bd0-f915bda793fd.png)

And my settings:

![exportlayers2](https://user-images.githubusercontent.com/4856029/65394641-67e71900-dd88-11e9-91dd-6dc7b6bd12f6.png)

BaseWheel is tagged "Background" and the upper two layer groups as "foreground"

However, this just produces 3 identical images, each named after the Layer Group name:

![BaseWheel](https://user-images.githubusercontent.com/4856029/65394681-d9bf6280-dd88-11e9-96f6-01922278c9a4.png)

Whereas, I'm aiming for it to have separate images, which consist of the background layer and then each of the separate foreground layer groups (not a composite of both)

Hope that makes sense! Any suggestions on how I could achieve this?

thanks

**Comment by stigzler** [comment]
Nemmind. Figured it. I took "Foreground" tags off the layer groups to be transposed:

![exportlayers3](https://user-images.githubusercontent.com/4856029/65448871-b1d80980-de31-11e9-816c-40859c8545d3.png)

Issue sorted. Thanks for a great plugin!

**Comment by khalim19** [comment]
Glad you got it working.

> I'm wondering if this is the same plugin that I used here:

It indeed is, but a very old version (2.5 I think).
