### ISSUE TITLE
Feature request: separate foreground for each layer group

### ISSUE THREAD

**Issue by skelder** [khalim19/gimp-plugin-export-layers#80]
Is there a way to set foreground for each layer group?

if not I think it would be cool to be able to set separate foreground/background for each layer group

Currently my solution was to set separate tags for each foreground in layer groups and add bunch of procedures that use those tags and turn each of them on/off to match the layer group I wanted to to export.

**Comment by khalim19** [comment]
This is currently not possible, only with a manual workaround as you described.

Once implemented, [this feature](https://github.com/khalim19/gimp-plugin-export-layers/issues/13) should allow you to specify, for example, which operations to apply to which layers or layer groups, which should also cover your case.

**Comment by skelder** [comment]
Thanks for letting me know!

I'll make sure to check out the feature you mentioned once it goes live.
