### ISSUE TITLE
"Ignore folder structure" also ignores layer path in the name

### ISSUE THREAD

**Issue by Necronomicron** [khalim19/gimp-plugin-export-layers#83]
Hello! I would like to be able to save files without subfolders yet to keep the names as "groupName-layerName". If I select "Ignore folder structure" then it is also ignored in the name.

GIMP 2.10.18, Export Layers 3.3.1, Windows 10 x64.

**Comment by khalim19** [comment]
Thanks for the report, this appears to be a bug. I'll see what I can do.

**Comment by khalim19** [comment]
I changed the default behavior such that the full layer path is now retained when "Ignore folder structure" is enabled. I'll add an option in the future to allow explicitly specifying "rename layers" as a procedure which allows bringing back the old behavior.

**Comment by khalim19** [comment]
From 3.3.2, "Ignore folder structure" now maintains the full path if `[layer path]` is specified as a pattern. You can restore the old behavior by adding a new "Rename layer" procedure after "Ignore folder structure" if needed.
