### ISSUE TITLE
[SOLVED] Menu entry not shown in Debian 10 / Gimp 2.10

### ISSUE THREAD

**Issue by speefak** [khalim19/gimp-plugin-export-layers#86]
System Debian 10
Gimpversion :  2.10.8-2     amd64 
Python version :  2.7.16-1     amd64  
Export layers version 3.3.1
 
I try to install export layers by Downloading the latest version an extract the archiv content to "/home/user/.config/GIMP/2.10/plug-ins" but i cant find the menu entry export layers in File Section or anywhere else ( like here : https://youtu.be/1zL-5tpGekM?t=147 ) 

I manually added a file usr/lib/gimp/2.0/interpreters/pygimp.interp and set the path - without success.

Solution : Missing package  >> gimp-python <<. Install it and export layers is show in menu ;)

**Comment by isaactzab** [comment]
Hello, I'm noob.
Where is located the gimp-python package? I googled and not found the repository.

**Comment by isaactzab** [comment]
I'am using ubuntu 20.04 and Gimp 2.10.18. Also I have installed python 2.7 and 3, I have modified the pygimp.interp file and i have no success.

**Comment by isaactzab** [comment]
Finally after a deep search a found a comment from the user daverove at
May 22 https://discuss.pixls.us/ forums and it works.

> Since this thread is the top hit for a Google search for the gimp-python problem, I’ll post the solution that I found. Ubuntu 18.10’s gimp-python can be manually downloaded and installed into Ubuntu 20.04. One other completely missing missing package, python-gtk2, also needs downloading. All other dependencies can be installed normally from 20.04. No security problems since it’s all from Ubuntu. No forced installation to ignore missing dependencies. “Heal Selection” works, and unlike the flatpak version, GMIC QT works.
``` wget http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-6_amd64.deb
wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gimp/gimp-python_2.10.8-2_amd64.deb

sudo apt install gimp gimp-plugin-registry gimp-gmic
sudo apt install python python-cairo python-gobject-2

sudo dpkg -i python-gtk2_2.24.0-6_amd64.deb
sudo dpkg -i gimp-python_2.10.8-2_amd64.deb
```

**Comment by hungryseashell** [comment]
For Manjaro or Arch users, there is the [python2-gimp](https://aur.archlinux.org/packages/python2-gimp) plugin that needs to be installed.

**Comment by khalim19** [comment]
Thanks, I updated the installation instructions to reflect this.
