### ISSUE TITLE
Frequent crashes when exporting has finished

### ISSUE THREAD

**Issue by Crystalwarrior** [khalim19/gimp-plugin-export-layers#90]
#### What went wrong?

Very often, when I export the images, the program crashes after the operation is successful. All of the images are exported properly regardless of the crash, so it only happens when the operation has properly finished.
![изображение](https://user-images.githubusercontent.com/3470436/91719877-bdce5e80-eb9e-11ea-911a-eb68a9c261bc.png)

#### If you can, tell us the steps to reproduce the problem.
Use the Export Layers plugin on Gimp 2.10.20. Crashes are inconsistent but frequent.

#### Configuration

Version of Export Layers: 3.3.1 (February 04, 2019)

Version of GIMP: Gimp 2.10.20

Operating system: Windos 10

**Comment by Crystalwarrior** [comment]
I believe I managed to reproduce this. It seems like it only raises unhandled exception error if you didn't save before exporting.

**Comment by khalim19** [comment]
Thanks for reporting this issue. The latest revision should fix this crash. Hopefully I'll make a new release soon.

**Comment by khalim19** [comment]
Fixed in 3.3.2.
