### ISSUE TITLE
Error on export from Export Layers

### ISSUE THREAD

**Issue by KHucks** [khalim19/gimp-plugin-export-layers#96]
#### What went wrong?
On Export Gimp crashes. But not with every set of settings. Here is one set that leads to a crash very often like every second or third time.

C:\Program Files\GIMP 2\bin\gimp-2.10.exe
fatal error: unhandled exception

#### If you can, tell us the steps to reproduce the problem.

Use attached file.
-> [Test Layer Export Plugin.zip](https://github.com/khalim19/gimp-plugin-export-layers/files/6425827/Test.Layer.Export.Plugin.zip)

go to file -> Export Layers...
Define Foreground, Background and a "hide" tag for the layer group that should not be exported
choose settings as shown on screenshot (they were saved in last gimp session and now show up as default)
-> ![2021-05-05 10_21_13-Window](https://user-images.githubusercontent.com/14946422/117114196-d32e0500-ad8b-11eb-9b2f-3176a0bf577c.png)

click export
Click export again with these settings.
![2021-05-05 10_23_56-Window](https://user-images.githubusercontent.com/14946422/117114388-16887380-ad8c-11eb-8419-cac6384f99a4.png)

Sometimes the error message at very top shows up crashing the whole of gimp. In some cases also these errror messages come up (I get the feeling it has something to do with saving the settings)
![2021-05-05 10_28_16-Window](https://user-images.githubusercontent.com/14946422/117115729-cd392380-ad8d-11eb-916c-38070b9e1183.png)

hope this helps to fix the bug. I love the plugin but this issue really kills the usability.

#### Configuration

Version of Export Layers: export_layers-3.3.1-windows.exe

Version of GIMP: GIMP 2.10.22

Operating system: Win 10 Professional

**Comment by desmarty** [comment]
(Sorry to the developer) As this plugin is out dated or may be it is inactive on current issues, I made scripts for the same purpose. Please find it in [Gimp Scripts - Export layers](https://github.com/desmarty/gimp_script ). (This is an essential part of gimp. So I had to develop it by myself. It is a script, so it may not be broken in future releases of gimp. I am working on other essential modules for gimp too. Hope it is helpful to someone. Thank you and again sorry to this developer as i am approximately promoting my repository here)

**Comment by khalim19** [comment]
Thanks for reporting this issue. The latest revision should fix this crash. I'll make a new bugfix release in a few days/weeks.

**Comment by khalim19** [comment]
Fixed in 3.3.2.
