### ISSUE TITLE
Export Layers not appearing in menu - error during startup

### ISSUE THREAD

**Issue by akc42** [khalim19/gimp-plugin-export-layers#97]
The following appears on the terminal after starting gimp from the command line (obviously its installed in my home directory config).

```
Traceback (most recent call last):
  File "/home/alan/.config/GIMP/2.10/plug-ins/export_layers.py", line 41, in <module>
    import gimpenums
ImportError: No module named gimpenums
gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
```

Version of Export Layers: 
I presume its 3.3.1 - latest download of a few minutes ago

Version of GIMP: 
2.10.22

Operating system: 
linux Debian Buster.

**Comment by kamdeb6x3** [comment]
Same issue for me still not found a solution

Export Layers version: 3.3.1
Operating system: ArchLinux on 5.10.68-1-lts kernel.

**Comment by ei14** [comment]
I fixed the issue by installing `python2-gimp` and `libffi7`.

**Comment by some-username-here1** [comment]
Is there any solution possible on Debian 11 (Bullseye)?

**Comment by brunetton** [comment]
Same under Ubuntu 21.10, no gimp python package (I guess this is bundeled with gimp now); and no "export layers" menu option

**Comment by brunetton** [comment]
## Workaround for Ubuntu

- do **not** use Ubuntu version (https://bugs.launchpad.net/ubuntu/+source/gimp/+bug/1881684)
- use [Flatpack](https://flatpak.org/) version
   - sudo apt install flatpack
   - sudo flatpak install https://flathub.org/repo/appstream/org.gimp.GIMP.flatpakref
   - flatpak run org.gimp.GIMP//stable

It can access to `~/.config/GIMP/2.10/plug-ins/` so loads the plugin :fireworks: 

## Documentation suggestion

I'll very probably make a PR to add to the doc a pre-require to check if Gimp Python is active: "check that you've Python-Fu entry in Filters menu.

![image](https://user-images.githubusercontent.com/86322/159173479-ef91ae65-a472-4e76-b629-5018afad4dea.png)

**Comment by khalim19** [comment]
Thanks for the information, I updated the installation instructions. It indeed looks like python-gimp packages and the like were removed from Ubuntu and the Flatpak installation worked for me as well. I'm assuming custom AppImages work, too, provided that they bundle Python 2.7 and other necessary GIMP-Python packages.
