### ISSUE TITLE
crashes on startup of GIMP, no "Export Layers" option in File menu

### ISSUE THREAD

**Issue by MaidLucy** [khalim19/gimp-plugin-export-layers#98]
Crashes on startup
```
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/plug-ins/export_layers.py", line 38, in <module>
    from export_layers import pygimplib
  File "/usr/lib/gimp/2.0/plug-ins/export_layers/pygimplib/__init__.py", line 33, in <module>
    from . import pglogging
  File "/usr/lib/gimp/2.0/plug-ins/export_layers/pygimplib/pglogging.py", line 34, in <module>
    str = unicode
NameError: name 'unicode' is not defined
gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
  File "/home/kosaki/.config/GIMP/2.10/plug-ins/gimp_ora_plus.py", line 88
    except OSError, e:
                  ^
SyntaxError: invalid syntax
gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
```

Version of Export Layers: latest git version

Version of GIMP: 2.10.24

Operating system: Arch Linux

**Comment by Lgmrszd** [comment]
Can confirm, having same issue.

**Comment by ilonachan** [comment]
Having a similar problem at least. Seems to me like the python version is causing trouble: for example `except OSError, e:` used to be valid in Python 2, but in Python 3 only `except OSError as e:` works.
It seems likely to me that converting this project to use Python 3 will fix the problem.

**Comment by Mengesh** [comment]
I solved it by installing `python2-gimp`

**Comment by khalim19** [comment]
Thanks for the heads-up, I'll update the installation instructions.

**Comment by khalim19** [comment]
Installation instructions have been updated in version 3.3.2.
